Task#50
Dasher83/Topic-Twister-Team-13 pull request #14
Opened 2023-04-26 20:37 UTC by MarianoLascares

[Task#50 Mantenimiento: Mejorar temporizador para que cuente tiempo incluso con la aplicación cerrada](https://team-13-quark.atlassian.net/browse/TT-50?atlOrigin=eyJpIjoiZWExMzgwOWY2ODgxNDQwZGIyYzIxNThkNDFiOTg2NzciLCJwIjoiaiJ9)

2023-04-27 13:58 UTC, Dasher83 commented on Assets/PlayTurn/Scripts/Timer/Timer.cs
> +        private DateTime _timeInit;
Esta variable quiere representar cual fue el momento en el cual el Timer empezó a contar.
El nombre actual podría mejorarse para ser más claro. Ejemplos: "_startDateTime", "_initialDateTime".

2023-04-27 14:03 UTC, Dasher83 commented on Assets/PlayTurn/Scripts/Timer/Timer.cs
> +        private TimeSpan _timerTime;
Mismo tipo de problema. El nombre no indica nada o se comunica de forma muy ambigua. Observando el código, uno puede inferir que esta variable quiere representar el lapso de tiempo que ha transcurrido desde el comienzo de conteo hasta el presente. O más abreviadamente, el tiempo transcurrido. Esto lleva a que un nombre de variable mucho más claro sería "_elapsedTime".

2023-04-27 15:34 UTC, Dasher83 commented on Assets/PlayTurn/Scripts/Timer/Timer.cs
> +
Acá veo un if vacío. No tiene sentido alguno. Si tenes una condición y queres negarla, negala. Podes usar el operador unitario de negación "!" o igualar la expresión booleana a falso "expresión == false". No deberías de crear una condición para después solo usar su else.

2023-04-27 15:42 UTC, Dasher83 commented on Assets/PlayTurn/Scripts/Timer/Timer.cs
> +        private bool DifferenceTimes()
No entiendo la justificación para que esta función retorne booleano. 
Cual es su intención? Actualizar el tiempo transcurrido y tomar las decisiones que respectan a qué debe mostrar la vista actualizando la propiedad NumericTime (la podemos renombrar la variable y propiedad a _secondsLeft & SecondsLeft respectivamente ya que hay variables / propiedades nuevas y necesitamos distinguir sus distintas intenciones). 
Volviendo al método, acá vemos que no necesita booleano para nada, puede ser una función void que se llame Countdown, porque es lo que hace, contar hacia atrás. Incluso si lo fueramos a dejar como un booleano, el nombre DifferenceTimes no transmite nada. No tengo idea de que hace al función solo mirando su firma (tipo de retorno + nombre + parámetros).

2023-04-27 15:45 UTC, Dasher83 commented on Assets/PlayTurn/Scripts/Timer/Timer.cs
> +            if (_timerTime.TotalSeconds > 60)
Este 60 por todos lados se le conoce como un número mágico. El remedio más simple ahora mismo sería tener una constante a nivel de clase que se llame TurnMaxDuration o TurnMaximumDuration y referenciarla siempre que quieras meter un 60 suelto. Estoy bastante seguro que en otra tarea de mantenimiento esto pasaría a un archivo o Scriptable object de constantes, pero por ahora restringamonos a evitar la repetición en este archivo actual con una constante local a nivel de clase.

2023-04-27 15:53 UTC, Dasher83 commented on Assets/PlayTurn/Scripts/Timer/Timer.cs
> +            }
Este condicional es inecesario. Ya preguntaste unas líneas más arriba si el tiempo transcurrido era mayor a 60, por lo que debe ser 60 o menos. Cualquier cálculo sobre el tiempo transcurrido va a ser cero o positivo. Si no es así, el condicional va a molestar para ver el comportamiento de la clase. Este bloque puede reducirse a solo la asignación de la propiedad NumericTime, que se va a renombrar a SecondsLeft.

2023-04-27 15:53 UTC, Dasher83 commented on Assets/PlayTurn/Scripts/Timer/Timer.cs
> +            }
No es necesario, se puede borrar perfectamente.

2023-04-27 15:56 UTC, Dasher83 requested changes
Se puede con poco esfuerzo mejorar mucho la legibilidad y la concretitud del código.
Dejé comentarios con freedback concreto.

2023-04-29 01:40 UTC, Damian-Bogarin commented on Assets/PlayTurn/Scripts/Timer/Timer.cs
> +            }
Esto lo que hace es quitarle, cada segundo la diferencia entre 60 y el tiempo que paso, para que vaya cayendo el tiempo segundo tras segundo.

2023-04-29 17:09 UTC, Dasher83 commented on Assets/PlayTurn/Scripts/Timer/Timer.cs
> +        private void DifferenceTimes()
Ahora la función en general hace lo que se esperaba que hiciera una cuenta atrás. Buen trabajo.
Favor de cambiar el nombre de la función a "Countdown" ya que lo que hace el método literalmente es contar atrás. 
Lo hace a través de restar fechas pero el efecto es contar atrás. DifferenceTimes no transmite nada.

2023-04-29 17:13 UTC, Dasher83 commented on Assets/PlayTurn/Scripts/Timer/Timer.cs
> +            }
Totalmente, el cuerpo del if, específicamente la línea 75 cumple esa función. Lo que es innecesario es envolverlo en el condicional de la línea 73. A lo sumo cumple una función de no empezar a restar hasta que haya pasado un segundo, pero esto no es deseable, ya que tendría que evaluar ese if muchas veces más posterior al pasaje del primer segundo y en todas esas pasadas va a dar false. Si notas algún comportamiento como que el reloj pasa enseguida de 59 a 60, se puede arreglar de otras formas y no debes preocuparte por ello en esta tarea específica.

2023-04-29 17:14 UTC, Dasher83 commented on Assets/PlayTurn/Scripts/Timer/Timer.cs
> +            else if (_elapsedTime.TotalSeconds >= 1 && !_invokedTimedOut)
Este else if podría solo tener su segundo componente "!_invokedTimedOut". La primer parte de la condición no es necesaria.

2023-04-29 17:15 UTC, Dasher83 requested changes
Arreglaste la mayoría de los problemas. Buen trabajo, solo te quedan un par de detalles.

2023-04-29 17:17 UTC, Dasher83 commented on Assets/PlayTurn/Scripts/Timer/Timer.cs
> +            }
Resuelvo este comentario para evitar confusión, ya que dejé uno nuevo en el código actualizado.

2023-04-29 18:44 UTC, Dasher83 commented on Assets/PlayTurn/Scripts/Timer/Timer.cs
> +        private void DifferenceTimes()
Se acuerda nombre SubstractTime

2023-04-29 18:58 UTC, Dasher83 approved these changes
💯

2023-04-29 18:59 UTC, merged