Task#110
Dasher83/Topic-Twister-Team-13 pull request #20
Opened 2023-05-08 22:44 UTC by Dasher83

[Link a tarea de jira](https://team-13-quark.atlassian.net/browse/TT-110)

2023-05-08 23:10 UTC, MarianoLascares commented on Assets/Home/Tests/HomeEditModeTests/CreateMatchSubUseCaseTests.cs
> +    private IdtoMapper<Match, MatchDto> _matchDtomapper;
u.u

2023-05-08 23:12 UTC, MarianoLascares commented on Assets/Home/Tests/HomeEditModeTests/CreateMatchSubUseCaseTests.cs
>          int botId = 2;
Hacer uso de constantes de configuración

2023-05-08 23:25 UTC, MarianoLascares commented on Assets/PlayTurn/Scripts/Presenters/StartTurnPresenter.cs
> +}
U.U

2023-05-08 23:28 UTC, MarianoLascares commented on Assets/PlayTurn/Scripts/Shared/Interfaces/IPlayTurnView.cs
> +}
O.o

2023-05-08 23:28 UTC, MarianoLascares commented on Assets/PlayTurn/Scripts/Shared/Interfaces/IStartTurnGatewayService.cs
> +}
T.T

2023-05-08 23:29 UTC, MarianoLascares commented on Assets/PlayTurn/Scripts/Shared/Interfaces/IStartTurnPresenter.cs
> +}
Falta espacio fin de archivo

2023-05-09 00:17 UTC, MarianoLascares requested changes
Revisar cambios menores comentados

2023-05-09 00:30 UTC, FerChaz commented on Assets/PlayTurn/Scripts/Shared/Interfaces/IStartTurnGatewayService.cs
> +}
n.n

2023-05-09 00:32 UTC, MarianoLascares approved these changes

2023-05-09 00:34 UTC, merged