Maquetacion: home & historial de partidas
Dasher83/Topic-Twister-Team-13 pull request #4
Opened 2023-04-04 21:23 UTC by MarianoLascares

creación de maquetas home y historial de partidas

2023-04-05 00:40 UTC, FerChaz requested changes
Aprovechando que no esta mergeado todavía, estaría bueno tomar el feedback de Eimi (Dueña de Producto)  para hacer las correcciones necesarias. Podemos seguir el diseño original de figma y consultarlo nuevamente por Discord. Pero fuera de eso, muy buen laburo!

2023-04-07 00:23 UTC, FerChaz approved these changes
Que buenos fixes que hicieron!!

2023-04-07 00:40 UTC, Dasher83 approved these changes
Buen laburo, temas menores quedaran registrados para futuro mantenimiento.
Muchas gracias gurices!

2023-04-07 00:40 UTC, FerChaz approved these changes
Todo correcto!

2023-04-07 00:41 UTC, merged